image: docker:24

default:
  tags:
    - docker_executor
  services:
    - docker:24-dind

variables:
  #stable kubectl version: $(wget -qO - https://dl.k8s.io/release/stable.txt)
  KUBECTL_VERSION: "v1.28.3"
  KIND_VERSION: "v0.20.0"
  CLUSTER_NAME: "my-test-cluster"
#  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - setup_and_run_tests
  - save_results

before_script:
  - echo "Installing kind"
  - wget -qO kind "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64"
  - chmod +x kind
  - mv kind /usr/local/bin/

  - echo "Installing kubectl"
  - wget -qO kubectl "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/

setup_and_run_tests:
  stage: setup_and_run_tests
  script:
    #if cluster will be ready before 300s, it will go further
    - kind create cluster --name $CLUSTER_NAME --config kind-config.yml --wait 300s
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - kubectl config set-cluster kind-$CLUSTER_NAME --insecure-skip-tls-verify=true
    - kubectl get nodes
    - kubectl cluster-info
    - kubectl get namespaces

  after_script:
    - kind delete cluster --name $CLUSTER_NAME

save_results:
  stage: save_results
  script: echo Meow results