image: amazoncorretto:17-al2-full

default:
  tags:
    - docker_executor
  services:
    - docker:dind

variables:
  KUBECTL_VERSION: "1.28.3" #$(curl -L -s https://dl.k8s.io/release/stable.txt)
  KIND_VERSION: "v0.20.0"
  CLUSTER_NAME: "my-test-cluster"

stages:
  - install_kind
  - create_k8s_cluster
  - install_kubectl
  - run_tests
  - save_results

install_kind:
  stage: install_kind
  script:
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/
    - kind version
#  variables:
#    PATH: /usr/local/bin:$PATH

create_k8s_cluster:
  stage: create_k8s_cluster
  script:
    - kind create cluster --name $CLUSTER_NAME

install_kubectl:
  stage: install_kubectl
  script:
    - curl -LO "https://dl.k8s.io/release/$(KUBECTL_VERSION)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - export KUBECONFIG="$(kind get kubeconfig-path --name $CLUSTER_NAME)"


run_tests:
  stage: run_tests
  script:
    - echo Meow
    - kubectl get nodes
    - echo Meoww
    - kubectl get nodes --insecure-skip-tls-verify=true
  after_script:
    - kind delete cluster --name $CLUSTER_NAME