image: docker:24.0.7

default:
  tags:
    - docker_executor
#    - shell_executor
  services:
   - name: docker:24.0.7-dind

variables:
  #$(wget -qO - https://dl.k8s.io/release/stable.txt)
  KUBECTL_VERSION: "v1.28.3"
  KIND_VERSION: "v0.20.0"
  CLUSTER_NAME: "my-test-cluster"

stages:
  - setup_and_run_tests
  - save_results

before_script:
  - echo "Installing kind"
  - wget -qO kind "https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64"
  - chmod +x kind
  - mv kind /usr/local/bin/

  - echo "Installing kubectl"
  - wget -qO kubectl "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
#  - export PATH="$PATH:$(pwd)"
  - echo $KUBECONFIG
#  - export KUBECONFIG="$(kind get kubeconfig-path --name $CI_PIPELINE_ID)"
#  - REAL_IP=$(ip route|awk '/default/ { print $3 }')
#  - sed -i -e "s/localhost/$REAL_IP/g" ~/.kube/config

setup_and_run_tests:
  stage: setup_and_run_tests
  script:
#if cluster will be ready before 300s, it will go further
    - kind create cluster --name $CLUSTER_NAME --wait 300s
    - echo Meow
    - kubectl get nodes
    - echo Meoww
    - kubectl get nodes --insecure-skip-tls-verify=true
  after_script:
    - kind delete cluster --name $CLUSTER_NAME

save_results:
  stage: save_results
  script: echo Meow results