image: docker:24

default:
  tags:
    - docker_executor
  services:
    - docker:24-dind

variables:
  #stable kubectl version: $(wget -qO - https://dl.k8s.io/release/stable.txt)
  KUBECTL_VERSION: "v1.28.3"
  KIND_VERSION: "v0.20.0"
  CLUSTER_NAME: "my-test-cluster"
#  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - setup_and_run_tests
  - publish_report_page

setup_and_run_tests:
  stage: setup_and_run_tests
  script:
#if cluster will be ready before 300s, it will go further
    - kind create cluster --name $CLUSTER_NAME --config kind-config.yml --wait 300s
    - sed -i -E -e 's/localhost|0\.0\.0\.0/docker/g' "$HOME/.kube/config"
    - kubectl config set-cluster kind-$CLUSTER_NAME --insecure-skip-tls-verify=true
    - kubectl get nodes
    - kubectl cluster-info
    - kubectl get namespaces

    - echo "Executing tests"
    - ./gradlew test
  after_script:
    - kind delete cluster --name $CLUSTER_NAME
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/build/reports/tests/test/
      - $CI_PROJECT_DIR/build/test-results/test/
    expire_in: 3 days

publish_report_page:
  stage: publish_report_page
  script: echo Meow results